#!/usr/bin/env bun

import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as url from "node:url";

const outputPath = url.fileURLToPath(new URL("../src/utils/mupdf-embedded.ts", import.meta.url));
const sourceMapping = `// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-mupdf.ts. Source installs resolve the package lazily.
export const embeddedMuPdfWasm: string | undefined = undefined;
export const embeddedMuPdfModule: string | undefined = undefined;
`;

export async function resetMuPdfAsset(): Promise<void> {
	await Bun.write(outputPath, sourceMapping);
}

export async function generateMuPdfAsset(): Promise<void> {
	const temporaryPath = `${outputPath}.tmp`;
	try {
		const markitModule = url.fileURLToPath(new URL("../vendor/markit-ai/dist/index.js", import.meta.url));
		const modulePath = Bun.resolveSync("mupdf", path.dirname(markitModule));
		const wasmPath = path.join(path.dirname(modulePath), "mupdf-wasm.wasm");
		await fs.access(wasmPath);
		await Bun.write(
			temporaryPath,
			`// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-mupdf.ts. Reset after compiling.
import wasmAsset from ${JSON.stringify(wasmPath)} with { type: "file" };
export const embeddedMuPdfWasm: string | undefined = wasmAsset;
export const embeddedMuPdfModule: string | undefined = ${JSON.stringify(modulePath)};
`,
		);
		await fs.rename(temporaryPath, outputPath);
	} catch (cause) {
		await resetMuPdfAsset();
		throw new Error("Unable to embed MuPDF WASM; install coding-agent's mupdf dependency before compiling.", {
			cause,
		});
	} finally {
		await fs.rm(temporaryPath, { force: true });
	}
}

if (import.meta.main) {
	if (process.argv.includes("--reset")) await resetMuPdfAsset();
	else await generateMuPdfAsset();
}
