#!/usr/bin/env bun

import { access, rename, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const outputPath = fileURLToPath(new URL("../src/utils/mupdf-embedded.ts", import.meta.url));
const sourceMapping = `// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-mupdf.ts. Source installs resolve the package lazily.
export const embeddedMuPdfWasm: string | undefined = undefined;
`;

export async function resetMuPdfAsset(): Promise<void> {
	await writeFile(outputPath, sourceMapping);
}

export async function generateMuPdfAsset(): Promise<void> {
	const temporaryPath = `${outputPath}.tmp`;
	try {
		const wasmPath = fileURLToPath(new URL("./mupdf-wasm.wasm", import.meta.resolve("mupdf")));
		await access(wasmPath);
		await writeFile(
			temporaryPath,
			`// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-mupdf.ts. Reset after compiling.
import wasmAsset from ${JSON.stringify(wasmPath)} with { type: "file" };
export const embeddedMuPdfWasm: string | undefined = wasmAsset;
`,
		);
		await rename(temporaryPath, outputPath);
	} catch (cause) {
		await resetMuPdfAsset();
		throw new Error("Unable to embed MuPDF WASM; install the pinned mupdf dependency before compiling.", { cause });
	} finally {
		await rm(temporaryPath, { force: true });
	}
}

if (import.meta.main) {
	if (process.argv.includes("--reset")) await resetMuPdfAsset();
	else await generateMuPdfAsset();
}
